### PR TITLE
@lennamau: did migrations, post for the projects, get the projects by id and post…

### PR DESCRIPTION
**Pull request by arunabenji29**
… for the actions work

### CODE REVIEW

**Comment by arunabenji29** [comment]
@lennamau : answers for the questions at answers.md

**Comment by arunabenji29** [comment]
@lennamau :MVP

**Comment by arunabenji29** [comment]
@lennamau : completed seeding for project and actions table

**Comment by arunabenji29** [comment]
@lennamau : crud operations for both the actions and the projects work

**Comment by arunabenji29** [comment]
@lennamau :stretch completed

**Comment by lennamau** [comment]
# Web DB Sprint
## MVP
- [x] Project Setup
- [x] Migrations for project and action
- [x] Post projects
- [x] Post actions
- [x] Get project by id with actions 

## Stretch
- [x] Remaining CRUD for projects and actions
- [x] Knex seeding
- [x] Support for contexts 

## What Looks Great
- Awesome work completing MVP and Stretch!
- Clean, uniform code
- Separated into routes and helper functions

## What Could Be Improved
- Comments in code to describe what it is doing

## Rating (1-3)
### 3

**Pull request merged**
